# place in .config/

add_newline = false

[directory]
style = "bold bright-yellow"
truncation_length = 4
truncation_symbol = "â€¦/"
read_only = " ðŸ”’"

[git_branch]
symbol = "î‚  "
style = "bold purple"

[git_status]
disabled = true

[username]
disabled = true
[hostname]
disabled = true


# Languages and frameworks
[nodejs]
symbol = "Node.js "
[python]
symbol = "î˜† "
[rust]
symbol = "Rust "
[golang]
symbol = "Go "
[java]
symbol = "Java "
[kotlin]
symbol = "Kotlin "
